# Generated by Django 6.0.1 on 2026-01-24 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price_stars', models.IntegerField()),
                ('duration_days', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Premium plan',
                'verbose_name_plural': 'Premium plans',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('premium_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.CreateModel(
            name='StarPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_payment_charge_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider_payment_charge_id', models.CharField(blank=True, default='', max_length=128)),
                ('currency', models.CharField(db_index=True, max_length=8)),
                ('total_amount', models.IntegerField()),
                ('invoice_payload', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='succeeded', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_payments', to='billing.telegramuser')),
            ],
            options={
                'verbose_name': 'Star payment',
                'verbose_name_plural': 'Star payments',
            },
        ),
    ]
