# Generated by Django 6.0.1 on 2026-01-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Start'), ('help', 'Help'), ('search', 'Search query'), ('search_result', 'Search result shown'), ('premium_open', 'Premium opened'), ('premium_click', 'Premium plan clicked'), ('invoice_sent', 'Invoice sent'), ('precheckout_ok', 'PreCheckout OK'), ('precheckout_fail', 'PreCheckout FAIL'), ('payment_success', 'Payment success'), ('payment_fail', 'Payment fail')], db_index=True, max_length=32, verbose_name='Тип события')),
                ('payload', models.JSONField(blank=True, help_text='Произвольные данные: query, plan_code, amount, errors и т.д.', null=True, verbose_name='Доп. данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата события')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_events', to='billing.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие бота',
                'verbose_name_plural': 'События бота',
                'ordering': ('-created_at',),
            },
        ),
    ]
