# Generated by Django 6.0.1 on 2026-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='payload',
            field=models.JSONField(blank=True, help_text='Произвольные данные: query, plan_code, amount, errors и т.д.', null=True, verbose_name='Дополнительные данные'),
        ),
    ]
