# Generated by Django 6.0.1 on 2026-01-21 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Не менять. Используется для обновления группы при импорте из Excel. Например: G0001', max_length=64, unique=True, verbose_name='ID из Excel')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('brands', models.CharField(blank=True, default='', help_text='Например: HOCO, Profit, Baseus', max_length=255, verbose_name='Бренды/линейки (через запятую)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Группа стёкол',
                'verbose_name_plural': 'Группы стёкол',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название стекла')),
                ('aliases_text', models.CharField(blank=True, default='', help_text='Например: a13; a13 5g; samsung a13', max_length=512, verbose_name='Алиасы (через ; или |)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glasses', to='catalog.glassgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Стекло',
                'verbose_name_plural': 'Стёкла',
                'ordering': ['name'],
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GlassAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255, verbose_name='Алиас')),
                ('normalized_alias', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Нормализованный алиас')),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.glass', verbose_name='Стекло')),
            ],
            options={
                'verbose_name': 'Алиас стекла',
                'verbose_name_plural': 'Алиасы стёкол',
                'ordering': ['alias'],
                'unique_together': {('glass', 'alias')},
            },
        ),
    ]
